global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'symfony'
    static_configs:
      - targets: ['symfony:9000']

  - job_name: 'python_worker'
    static_configs:
      - targets: ['python_worker:8000']